#! /bin/sh

alias rconfig='source .`basename $SHELL`rc'

alias ls='ls --color=auto'
alias la='ls -A'
alias ll='ls -lh'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias d='du -h --max-depth=1 | sort -h'

alias launch_agent='eval `ssh-agent`; ssh-add'
alias rdk='rdesktop -u simaticj -d LDTIMA.IMAG.FR -k fr -g 1266x768 wtstima-1.imag.fr'
alias kill_skype='kill -9 $(ps -e | grep skype | cut -d" " -f2)'

alias texcompile='latexmk -pdf -shell-escape *.tex'
alias texclean='latexmk -c; rm -rf *.run.xml *.nav *.snm dot _minted-top *.bbl figures/gen/*.* figures/gen/*/*; find . -name **~ -exec rm {} \;'

# Arch aliases
alias xlock='i3lock -c 603C7D -e'
#alias jabref='jabref -s'
alias netsw='sudo netctl switch-to'
alias netcut="sudo ip link set wlp2s0 down"

#alias emacs='emacsclient -t'
alias e='emacsclient -t'
alias remacs='/snap/bin/emacs --daemon; e'

# I don't know how to type
alias eamcs='emacs'
alias snv='svn'

alias gs="gst"
export WORK_GIT=$HOME/git
alias vpy3="pushd $WORK_GIT; source activate_python3_venv; popd"
alias vpy2="pushd $WORK_GIT; source activate_python2_venv; popd"

alias config='/usr/bin/git --git-dir=$HOME/.myconfigs/ --work-tree=$HOME'

alias reconnect='sudo ip link set wlp2s0 down; sudo netctl restart '
alias rmouse='sudo modprobe -r psmouse; sudo modprobe psmouse proto=imps '

alias auei='$WORK_GIT/coeur_io/linux/clavier_precedent'
alias qsdf='$WORK_GIT/coeur_io/linux/clavier_coeur_io'

main=eDP-1
screen1=DP-1-8
screen2=DP-1-1
alias single_monitor='xrandr --output $screen1 --off --output $screen2 --off; sleep 1; xrandr --output $main --auto'
alias dual_monitors='xrandr --output $screen1 --auto --right-of $main'
alias triple_monitors='xrandr --output $screen2 --auto --right-of $screen1'
alias steam='./.steam/steam/steam.sh'

alias bat="batcat"
